---
alias: cgtp
scripts:
  # block of commands to build this repo/branch on the CI server
  build: |
    npm run build
  # block of commands to test this repo/branch on the CI server
  test: |
    npm run test
  # block of commands to execute after this repo/branch is cloned to the CI server
  on_clone: ""
  # block of commands to execute on the CI server prior to deploying this repo/branch to the garden
  on_deploy: ""
  # block of commands to execute on the CI server when removing a deployment of this repo/branch
  on_remove: ""