---
alias: cgtp
scripts:
  # block of commands to build this repo/branch on the CI server
  build: |
    npm run build
  # block of commands to test this repo/branch on the CI server
  test: |
    npm run test
  # block of commands to execute after this repo/branch is cloned to the CI server
  after_clone: ""
  # block of commands to execute before this repo/branch is deployed to container(s)
  before_deploy: ""
  # block of commands to execute after this repo/branch is deployed to container(s)
  after_deploy: ""
  # block of commands to execute on the CI server before removing a deployment of this repo/branch
  before_remove: ""
  # block of commands to execute on the CI server after removing a deployment of this repo/branch
  after_remove: ""
