---
version: '2'

services:
  web:
    image: "{{ image }}"
    ports:
      - "0:3000"
    volumes:
      - "/opt/deployments/{{ subdomain }}:/var/www/project:rw"
    labels:
      - "traefik.frontend.rule=Host:{{ subdomain }}.{{ domain }}"
      - "traefik.frontend.entryPoints=http,https"
      - "timestamp={{ timestamp }}"
